# Generated by Django 2.2 on 2022-11-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20221125_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='skill_1',
            field=models.ImageField(default='images/none/noimg.jpg', upload_to='images'),
        ),
    ]
