# Generated by Django 2.2 on 2022-11-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20221125_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='skill_2',
            field=models.ImageField(default='images/none/noimg.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='build',
            name='skill_3',
            field=models.ImageField(default='images/none/noimg.jpg', upload_to='images'),
        ),
    ]
