# Generated by Django 2.2 on 2022-11-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20221127_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='skill_1',
            field=models.ImageField(default='images/none/noimg.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='build',
            name='skill_2',
            field=models.ImageField(default='images/none/noimg.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='build',
            name='skill_3',
            field=models.ImageField(default='images/none/noimg.jpg', upload_to='images/'),
        ),
    ]
