# Generated by Django 2.2 on 2022-11-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20221128_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='skill_1',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='build',
            name='skill_2',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='build',
            name='skill_3',
            field=models.CharField(max_length=1000),
        ),
    ]
