# Generated by Django 4.1.2 on 2022-10-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAPI', '0002_alter_bookdata_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdata',
            name='image',
            field=models.ImageField(default='images/none/noimg.jpg', upload_to='images'),
        ),
    ]
