# Generated by Django 2.2 on 2022-10-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbies',
            name='hobby_image',
            field=models.CharField(default='https://www.iesabroad.org/files/blog/images/amueller/2017-10-23/default_featured_image_29.jpg', max_length=500),
        ),
    ]
