# Generated by Django 2.2 on 2022-10-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0002_hobbies_hobby_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.CharField(default='https://c4.wallpaperflare.com/wallpaper/715/222/467/laptop-macintosh-neon-keyboards-wallpaper-preview.jpg', max_length=500),
        ),
    ]
